const oldSentences = [
    // "L\'éducation est le fondement de tout :cod :verb.",
    // "Chaque jour est une chance de :verb son :cod.",
    // "La persévérance est la clé pour :verb tout :cod.",
    // "L\'amitié est un trésor qui ne perd jamais de :cod :verb.",
    // "La créativité est le pouvoir de :verb son :cod.",
    // "La confiance est la base d\'une relation solide entre :cod et :cod.",
    // "La sagesse consiste à :verb le :cod avec discernement.",
    // "Le bonheur réside dans la capacité de :verb chaque petit :cod.",
    // "Le courage est la force de :verb malgré :cod.",
    // "L\'humilité est la clé pour :verb chaque :cod de la vie.",
    // "Chaque rêve est un :cod qui :verb à réalité.",
    // "L\'empathie est la capacité de :verb le monde à travers les yeux du :cod.",
    // "Le :cod est la toile vierge que nous pouvons :verb à notre guise.",
    // "Chaque moment de :cod est une occasion de :verb une nouvelle histoire.",
    // "La :cod est la clé qui ouvre la porte du :verb intérieur.",
    // "La :cod de soi est le premier pas vers la :verb personnelle.",
    // "L\'optimisme est le carburant qui alimente le :cod à chaque étape.",
    // "La :cod est le guide silencieux vers la :verb intérieure.",
    // "Chaque échec est un :cod qui :verb vers la réussite.",
    // "La :cod est la lanterne qui éclaire le chemin du :verb.",
    // "L\'inspiration est un :cod qui :verb les rêves en réalité.",
    // "Le :cod de l\'amour :verb toutes les barrières.",
    // "La :cod est la boussole qui nous guide à travers le :verb.",
    // "Chaque défi est une invitation à :verb un :cod extraordinaire.",
    // "La :cod est le secret du véritable :verb de soi.",
    // "La gratitude est la clé pour :verb chaque :cod de la vie.",
    // "Le :cod du temps est un trésor qui ne se :verb jamais.",
    // "L\'humour est un :cod qui :verb les fardeaux de la vie.",
    // "La :cod est le carburant de la créativité qui :verb sans limites.",
    // "La :cod du pardon :verb les chaînes du passé.",
    // "Chaque jour est une opportunité de :verb son :cod positivement.",
    // "La :cod est le miroir de l\'âme qui :verb au-delà des apparences.",
    // "Le :cod du savoir :verb les portes de l\'avenir.",
    // "L\'énergie positive est le :cod qui :verb le quotidien.",
    // "La :cod du changement est le seul constant :verb la vie.",
    // "Chaque aube est une promesse de :verb un nouveau :cod.",
    // "La :cod du courage :verb les frontières de l\'impossible.",
    // "La curiosité est le :cod de la découverte qui :verb l\'esprit.",
    // "Le :cod du silence :verb des messages plus forts que les mots.",
    // "Chaque rire est une note de musique dans la symphonie du :cod.",
    // "L\'amélioration continue est le :cod qui :verb vers l\'excellence.",
    // "La :cod est la force invisible qui :verb à travers l\'adversité.",
    // "Le :cod de la patience :verb des fruits doux avec le temps.",
    // "La :cod du respect :verb des ponts vers des relations solides.",
    // "Chaque épreuve est un :cod qui :verb le caractère.",
    // "La :cod du lâcher-prise :verb les ailes de la liberté intérieure.",
    // "Le :cod du leadership :verb des traces inspirantes pour suivre.",
    // "La :cod du présent :verb la clé du bonheur immédiat.",
    // "Chaque rêve est un :cod qui :verb le voyage de l\'âme.",
    // "Le :cod de la gentillesse :verb des vagues d\'amour autour de soi.",
    // "La :cod du savoir-faire :verb des portes vers l\'accomplissement.",
    // "L\'authenticité est le :cod qui :verb des connexions sincères.",
    // "La :cod de la volonté :verb les montagnes de l\'adversité.",
    // "Chaque sourire est une fenêtre ouverte vers le :cod intérieur.",
    // "La :cod du bonheur :verb des éclats de lumière dans l\'obscurité.",
    // "Le :cod du talent :verb des horizons infinis d\'expression.",
    // "La :cod du discernement :verb les chemins de la sagesse.",
    // "Chaque émotion qui :verb l\' est un :unPl :codexpérience humaisn, codSgexpérience humaine.",
    // "La :cod du partage :verb des liens indissolubles entre les âmes.",
    // "Le :cod du succès :verb des marches vers l\'accomplissement.",
    // "La :cod du mystère :verb des intrigues dans le livre de la vie.",
    // "Chaque larme est un poème écrit sur le :cod du cœur.",
    // "La :cod du pardon :verb les cicatrices de l\'âme.",
    // "La :cod du savoir-vivre :verb les portes de l\'harmonie sociale.",
    // "Chaque pas est une avancée vers le :cod de soi.",
    // "Le :cod de la motivation ardents de la réalisation :verb verPlb des feux.s", desSg feux.",
    // "La :cod du discernement :verb les ombres de l\'incertitude.",
    // "La :cod du savoir-être :verb les nuances de la personnalité.",
    // "Chaque moment de paix est un :cod qui :verb l\'âme.",
    // "Le :cod du progrès :verb des chemins vers un avenir meilleur.",
    // "La :cod du savoir-penser :verb les horizons de la compréhension.",
    // "La :cod du changement :verb des ailes aux rêves.",
    // "Chaque épreuve est un :cod qui :verb la force intérieure.",
    // "La :cod du discernement :verb les échos du silence.",
    // "Le :cod du dévouement :verb des ponts vers des lendemains radieux.",
    // "La :cod du respect :verb les graines de l\'harmonie.",
    // "Chaque expérience est un :cod qui :verb le livre de la vie.",
    // "La :cod du temps :verb des chapitres inoubliables.",
    // "Le :cod du leadership :verb des traces lumineuses dans l\'ombre.",
    // "La :cod du savoir-devenir :verb les portes de la transformation.",
    // "Chaque sourire est un :cod qui :verb la journée.",
    // "La :cod du courage :verb les sommets de la bravoure.",
    // "La :cod du discernement :verb les étoiles dans la nuit.",
    // "Le :cod de la résilience :verb des oasis après la tempête.",
    // "La :cod du savoir-s\'aimer :verb les portes de l\'épanouissement.",
    // "Chaque défaut est un :cod qui :verb vers la perfection.",
    // "La :cod du respect :verb les fondations de la coexistence.",
    // "Le :cod de la simplicité :verb des trésors dans la modestie.",
    // "La :cod du savoir-servir :verb les chemins de la générosité.",
    // "La :cod du discernement :verb les couleurs de la vérité.",
    // "Chaque étoile est un :cod qui :verb la voie dans l\'obscurité.",
    // "La :cod du savoir-vivre :verb les portes de l\'harmonie sociale.",
    // ":cod_det sont des :cod_det qui nous aident à :verb.",
];

const templates = [
    ":cod_det est :cod_det de chaque instants",
    "Chaque :cod est une occasion :verb_det :cod_det plus fort",
    ":cod est :cod_det qui :verb sans explication",
    "Chaque défi est une opportunité :verb_det :cod_det",
    "La patience est la clé pour :verb :cod_det",
];

const cods = [
    { genre: "m", mot_sing: "bonheur", mot_plu: "bonheurs", det_sing: "le ", det_plu: "les" },
    { genre: "m", mot_sing: "changement", mot_plu: "changements", det_sing: "le ", det_plu: "les" },
    { genre: "m", mot_sing: "coeur", mot_plu: "coeurs", det_sing: "le ", det_plu: "les" },
    { genre: "m", mot_sing: "courage", mot_plu: "courages", det_sing: "le ", det_plu: "les" },
    { genre: "m", mot_sing: "défi", mot_plu: "défis", det_sing: "le ", det_plu: "les" },
    { genre: "m", mot_sing: "dévouement", mot_plu: "dévouements", det_sing: "le ", det_plu: "les" },
    { genre: "m", mot_sing: "discernement", mot_plu: "discernements", det_sing: "le ", det_plu: "les" },
    { genre: "f", mot_sing: "énergie", mot_plu: "énergies", det_sing: "l\'", det_plu: "les" },
    { genre: "f", mot_sing: "épreuve", mot_plu: "épreuves", det_sing: "l\'", det_plu: "les" },
];

const verbs = [
    {
        infinitif: "abandonner",
        det: "d\'",
        conjugaisons: {
            present: {
                je: "abandonne",
                tu: "abandonnes",
                il_elle: "abandonne",
                elle: "abandonne",
                on: "abandonne",
                nous: "abandonnons",
                vous: "abandonnez",
                ils_elles: "abandonnent",
            }
        },
    },
    {
        infinitif: "accepter",
        det: "d\'",
        conjugaisons: {
            present: {
                je: "accepte",
                tu: "acceptes",
                il_elle: "accepte",
                elle: "accepte",
                on: "accepte",
                nous: "acceptons",
                vous: "acceptez",
                ils_elles: "acceptent",
            },
        },
    },
];